In [14]:
import wandb
import pandas as pd
import numpy as np

modelname = "Clip"
addon = "-GPE"  # 
entity = "cardiors"
project = "gatedsymile"

group_names = [
    f"CV-0-{modelname}{addon}-pair-MIMIC-IV",
    f"CV-1-{modelname}{addon}-pair-MIMIC-IV",
    f"CV-2-{modelname}{addon}-pair-MIMIC-IV",
    f"CV-3-{modelname}{addon}-pair-MIMIC-IV",
    f"CV-4-{modelname}{addon}-pair-MIMIC-IV",
]
api = wandb.Api()
metric = "test/acc_top1"

rows = []
for group in group_names:
    # get runs in this group
    runs = api.runs(f"{entity}/{project}", {"group": group})

    # parse split/method from the group string
    parts = group.split("-")
    split = parts[1]          # "0", "1", "2"
    method = parts[2]         # "GatedSymile"
    split = f"CV-{split}"     # make it "CV-0" etc.

    for run in runs:
        summary = dict(run.summary)

        # put the metric into a column named exactly like `metric`
        rows.append({
            "id": run.id,
            "name": run.name,
            "group": run.group,
            "state": run.state,
            "method": method,
            "split": split,
            metric: summary.get(metric, np.nan),
        })

df = pd.DataFrame(rows)
        
# filter df to metric > 0.4
df = df[df[metric] > 0.4]

display(df)


print("rows:", len(df))
print(df)
print(df[["split", "method", metric]].head())

# 1) aggregate seeds within (method, split)
agg = (df.dropna(subset=[metric])
         .groupby(["method", "split"])[metric]
         .agg(["mean", "count"])
         .reset_index())

# optional sanity check: expect 3 seeds per cell
print(agg.pivot(index="split", columns="method", values="count"))

# 2) wide table: one row per split, columns=methods
wide = agg.pivot(index="split", columns="method", values="mean").sort_index()
display(wide)

# Method-wise mean +/- stderr
for m in [modelname]:
    x = wide[m].dropna().values.astype(float)
    K = x.size
    mean_x = x.mean()
    stderr_x = x.std(ddof=1) / np.sqrt(K)
    print(f"{m}: {mean_x:.6f} ± {stderr_x:.6f} (stderr, K={K})")

,id,name,group,state,method,split,test/acc_top1
0,swov4q5o,mild-dust-13418,CV-0-Clip-GPE-pair-MIMIC-IV,finished,Clip,CV-0,0.699674
1,dhlapdlu,fluent-yogurt-13417,CV-0-Clip-GPE-pair-MIMIC-IV,finished,Clip,CV-0,0.699674
2,xpkd1k48,royal-glade-13416,CV-0-Clip-GPE-pair-MIMIC-IV,finished,Clip,CV-0,0.688786
3,o7colo4t,young-breeze-13421,CV-1-Clip-GPE-pair-MIMIC-IV,finished,Clip,CV-1,0.696670
4,2hkja7ws,dauntless-armadillo-13420,CV-1-Clip-GPE-pair-MIMIC-IV,finished,Clip,CV-1,0.693076
5,loew0dxw,dry-haze-13419,CV-1-Clip-GPE-pair-MIMIC-IV,finished,Clip,CV-1,0.691079
6,s5qfvsbl,hardy-dream-13424,CV-2-Clip-GPE-pair-MIMIC-IV,finished,Clip,CV-2,0.706482
7,k67egmii,cosmic-elevator-13423,CV-2-Clip-GPE-pair-MIMIC-IV,finished,Clip,CV-2,0.693263
8,67lkh1ck,proud-silence-13422,CV-2-Clip-GPE-pair-MIMIC-IV,finished,Clip,CV-2,0.705447
9,8lksq02b,comfy-snowball-13427,CV-3-Clip-GPE-pair-MIMIC-IV,finished,Clip,CV-3,0.711480
10,z57av57c,clean-salad-13426,CV-3-Clip-GPE-pair-MIMIC-IV,finished,Clip,CV-3,0.701940
11,49z1s8iv,restful-haze-13425,CV-3-Clip-GPE-pair-MIMIC-IV,finished,Clip,CV-3,0.709075
12,h6j2l4hb,usual-shadow-13430,CV-4-Clip-GPE-pair-MIMIC-IV,finished,Clip,CV-4,0.696144
13,yorroqvw,lyric-fire-13429,CV-4-Clip-GPE-pair-MIMIC-IV,finished,Clip,CV-4,0.697569
14,kcl09m2d,wise-tree-13428,CV-4-Clip-GPE-pair-MIMIC-IV,finished,Clip,CV-4,0.686881

rows: 15
          id                       name                        group  \
0   swov4q5o            mild-dust-13418  CV-0-Clip-GPE-pair-MIMIC-IV
1   dhlapdlu        fluent-yogurt-13417  CV-0-Clip-GPE-pair-MIMIC-IV
2   xpkd1k48          royal-glade-13416  CV-0-Clip-GPE-pair-MIMIC-IV
3   o7colo4t         young-breeze-13421  CV-1-Clip-GPE-pair-MIMIC-IV
4   2hkja7ws  dauntless-armadillo-13420  CV-1-Clip-GPE-pair-MIMIC-IV
5   loew0dxw             dry-haze-13419  CV-1-Clip-GPE-pair-MIMIC-IV
6   s5qfvsbl          hardy-dream-13424  CV-2-Clip-GPE-pair-MIMIC-IV
7   k67egmii      cosmic-elevator-13423  CV-2-Clip-GPE-pair-MIMIC-IV
8   67lkh1ck        proud-silence-13422  CV-2-Clip-GPE-pair-MIMIC-IV
9   8lksq02b       comfy-snowball-13427  CV-3-Clip-GPE-pair-MIMIC-IV
10  z57av57c          clean-salad-13426  CV-3-Clip-GPE-pair-MIMIC-IV
11  49z1s8iv         restful-haze-13425  CV-3-Clip-GPE-pair-MIMIC-IV
12  h6j2l4hb         usual-shadow-13430  CV-4-Clip-GPE-pair-MIMIC-IV
13  yorroqvw           lyric-fire-13429  CV-4-Clip-GPE-pair-MIMIC-IV
14  kcl09m2d            wise-tree-13428  CV-4-Clip-GPE-pair-MIMIC-IV

       state method split  test/acc_top1
0   finished   Clip  CV-0       0.699674
1   finished   Clip  CV-0       0.699674
2   finished   Clip  CV-0       0.688786
3   finished   Clip  CV-1       0.696670
4   finished   Clip  CV-1       0.693076
5   finished   Clip  CV-1       0.691079
6   finished   Clip  CV-2       0.706482
7   finished   Clip  CV-2       0.693263
8   finished   Clip  CV-2       0.705447
9   finished   Clip  CV-3       0.711480
10  finished   Clip  CV-3       0.701940
11  finished   Clip  CV-3       0.709075
12  finished   Clip  CV-4       0.696144
13  finished   Clip  CV-4       0.697569
14  finished   Clip  CV-4       0.686881
  split method  test/acc_top1
0  CV-0   Clip       0.699674
1  CV-0   Clip       0.699674
2  CV-0   Clip       0.688786
3  CV-1   Clip       0.696670
4  CV-1   Clip       0.693076
method  Clip
split
CV-0       3
CV-1       3
CV-2       3
CV-3       3
CV-4       3

method      Clip
split
CV-0    0.696045
CV-1    0.693608
CV-2    0.701731
CV-3    0.707498
CV-4    0.693532

Clip: 0.698483 ± 0.002702 (stderr, K=5)